#!/usr/bin/env python3
"""
Smart Requirements Builder for Railway Deployment
Merges core and ML requirements while maintaining compatibility
"""

import os
from pathlib import Path

def build_requirements():
    """Merge requirements-core.txt and requirements-ml-active.txt into requirements.txt"""
    
    backend_dir = Path(__file__).parent
    
    # File paths
    core_file = backend_dir / "requirements-core.txt"
    ml_file = backend_dir / "requirements-ml-active.txt"
    output_file = backend_dir / "requirements.txt"
    
    # Read existing files
    core_content = core_file.read_text() if core_file.exists() else ""
    ml_content = ml_file.read_text() if ml_file.exists() else ""
    
    # Build the merged requirements
    merged_content = f"""# PHASE 1B REQUIREMENTS - Auto-generated by build-requirements.py
# DO NOT EDIT MANUALLY - Edit requirements-core.txt and requirements-ml-active.txt instead

# =============================================================================
# CORE DEPENDENCIES (from requirements-core.txt)
# =============================================================================
{core_content}

# =============================================================================  
# PHASE 1B ML DEPENDENCIES (from requirements-ml-active.txt)
# =============================================================================
{ml_content}

# =============================================================================
# BUILD INFO
# =============================================================================
# Generated: {core_file.stat().st_mtime if core_file.exists() else 'N/A'} (core) + {ml_file.stat().st_mtime if ml_file.exists() else 'N/A'} (ML)
# Total packages: ~40 packages, ~1GB deployment size
# Expected Railway build time: 6-8 minutes (first build), 1-3 minutes (code changes)
# Docker optimization: Use Dockerfile.ultra-optimized for maximum caching
"""

    # Write merged file
    output_file.write_text(merged_content)
    
    # Count packages
    core_packages = [line.strip() for line in core_content.split('\n') 
                    if line.strip() and not line.strip().startswith('#') and '==' in line]
    ml_packages = [line.strip() for line in ml_content.split('\n') 
                  if line.strip() and not line.strip().startswith('#') and '==' in line]
    
    print("[SUCCESS] Requirements merged successfully!")
    print(f"Core packages: {len(core_packages)}")
    print(f"ML packages: {len(ml_packages)}")
    print(f"Total packages: {len(core_packages) + len(ml_packages)}")
    print(f"Output: {output_file}")
    print("Ready for Railway deployment!")

if __name__ == "__main__":
    build_requirements()