[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "cd /app && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt",
    "alembic upgrade head"
] 